# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20180330_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
