# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_course_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
    ]
