# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180330_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(),
        ),
    ]
